// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2.1
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Orm.Testing.Entities
{
    using Startitecture.Orm.Common;
    using Startitecture.Orm.Schema;

    /// <summary>
    /// The DomainAggregateFlagAttribute entity POCO.
    /// </summary>
    [Table("DomainAggregateFlagAttribute", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("storm.Reverse.POCO.Generator", "1.0.0")]
    public partial class DomainAggregateFlagAttributeRow : EntityBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DomainAggregateFlagAttributeRow"/> class.
        /// </summary>
        public DomainAggregateFlagAttributeRow()
        {
        }

        /// <summary>
        /// Gets or sets the DomainAggregateId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"DomainAggregateId", Order = 1, TypeName = "int")]
        [Index(@"PK_DomainAggregateFlagAttribute", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Domain aggregate ID")]
        public int DomainAggregateId { get; set; }

        /// <summary>
        /// Gets or sets the FlagAttributeId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"FlagAttributeId", Order = 2, TypeName = "int")]
        [Index(@"PK_DomainAggregateFlagAttribute", 2, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Flag attribute ID")]
        public int FlagAttributeId { get; set; }
    }

}
// </auto-generated>
