# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Startitecture.ORM build (storm)!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DownloadSecureFile@1
  name: coreSignCertificate
  displayName: 'Download Startitecture.Core signing certificate'
  inputs:
    secureFile: 'Startitecture.Core.pfx'

- powershell: |
    #Convert the Secure password that's presented as plain text back into a secure string
    $pwd = ConvertTo-SecureString -String $env:CORE_CERT_PASSWORD -Force -AsPlainText
    
    #Create PFX file from Certificate Variable
    New-Item Temp-Certificate.pfx -Value "$(coreSignCertificate.secureFilePath)"
    
    #Import the PFX certificate from the newly created file and password. Read the thumbprint into variable
    $Thumbprint = (Import-PfxCertificate -CertStoreLocation Cert:\CurrentUser\My -FilePath Temp-Certificate.pfx -Password $pwd).Thumbprint
    
    Write-Host $Thumbprint
    
    #Rest of Script below or set environment variable for rest of Pipeline
    Write-Host "##vso[task.setvariable variable=Thumbprint]$Thumbprint"
  env: 
    CORE_CERT_PASSWORD: $(CoreCertificate-Password)

- task: NuGetInstaller@0

- task: NuGetCommand@2

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    configuration: 'release'
    platform: 'any cpu'