# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Startitecture.ORM build (storm)!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: NuGetInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
     
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'