# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetInstaller@0

- task: NuGetCommand@2

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    configuration: 'release'
    platform: 'any cpu'

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestStable'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testFiltercriteria: 'TestCategory!="Integration"'
    codeCoverageEnabled: true
    runOnlyImpactedTests: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TEST-*.xml'
    mergeTestResults: true
    testRunTitle: 'Storm-CI'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Startitecture.Core.csproj;**/Startitecture.Resources.csproj'
    versioningScheme: 'off'
    includeReferencedProjects: true
    includeSymbols: true