//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Startitecture.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Startitecture.Resources.ActionMessages", typeof(ActionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuse Active Queue.
        /// </summary>
        public static string ActiveQueueReuse {
            get {
                return ResourceManager.GetString("ActiveQueueReuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use existing active queue {0}.
        /// </summary>
        public static string ActiveQueueReuseDescription {
            get {
                return ResourceManager.GetString("ActiveQueueReuseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowQueueCreation.
        /// </summary>
        public static string AllowQueueCreation {
            get {
                return ResourceManager.GetString("AllowQueueCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} queue because no queues were available..
        /// </summary>
        public static string AllowQueueCreationForEmptyPool {
            get {
                return ResourceManager.GetString("AllowQueueCreationForEmptyPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} queue for pool count {1} &lt; max count {2}..
        /// </summary>
        public static string AllowQueueCreationForMaxCount {
            get {
                return ResourceManager.GetString("AllowQueueCreationForMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} queue {1} for response latency ({2} vs. {3})..
        /// </summary>
        public static string AllowQueueCreationForResponseLatency {
            get {
                return ResourceManager.GetString("AllowQueueCreationForResponseLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} queue {1} for min count {2}..
        /// </summary>
        public static string AllowQueueForMinCount {
            get {
                return ResourceManager.GetString("AllowQueueForMinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DenyQueueCreation.
        /// </summary>
        public static string DenyQueueCreation {
            get {
                return ResourceManager.GetString("DenyQueueCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denying {0} queue creation for pool count {1} &gt;= max count {2}.
        /// </summary>
        public static string DenyQueueCreationForMaxCount {
            get {
                return ResourceManager.GetString("DenyQueueCreationForMaxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denying {0} queue creation {1} for resources (CPU {2:F2}%)..
        /// </summary>
        public static string DenyQueueCreationForResourcesCpu {
            get {
                return ResourceManager.GetString("DenyQueueCreationForResourcesCpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denying {0} queue creation {1} for resources (Failure Rate {2:F2}%)..
        /// </summary>
        public static string DenyQueueCreationForResourcesFailureRate {
            get {
                return ResourceManager.GetString("DenyQueueCreationForResourcesFailureRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denying {0} queue {1} for response latency ({2} vs. {3})..
        /// </summary>
        public static string DenyQueueCreationForResponseLatency {
            get {
                return ResourceManager.GetString("DenyQueueCreationForResponseLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuse Idle Queue.
        /// </summary>
        public static string IdleQueueReused {
            get {
                return ResourceManager.GetString("IdleQueueReused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use existing idle queue {0}.
        /// </summary>
        public static string IdleQueueReusedAction {
            get {
                return ResourceManager.GetString("IdleQueueReusedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Queue.
        /// </summary>
        public static string NewQueueUse {
            get {
                return ResourceManager.GetString("NewQueueUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use new queue {0}.
        /// </summary>
        public static string NewQueueUseDescription {
            get {
                return ResourceManager.GetString("NewQueueUseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed.
        /// </summary>
        public static string PolicyAllowsRequest {
            get {
                return ResourceManager.GetString("PolicyAllowsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string PolicyDeniesRequest {
            get {
                return ResourceManager.GetString("PolicyDeniesRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing all {0} items from the repository..
        /// </summary>
        public static string RemovingAllItemsFromRepository {
            get {
                return ResourceManager.GetString("RemovingAllItemsFromRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing the first matching {0} in the repository..
        /// </summary>
        public static string RemovingFirstItemFromRepository {
            get {
                return ResourceManager.GetString("RemovingFirstItemFromRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing any matching {0} items from the repository..
        /// </summary>
        public static string RemovingItemsFromRepository {
            get {
                return ResourceManager.GetString("RemovingItemsFromRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing {0} to queue &apos;{1}&apos;..
        /// </summary>
        public static string RoutingMessageToQueue {
            get {
                return ResourceManager.GetString("RoutingMessageToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving a {0} to the repository..
        /// </summary>
        public static string SavingItemInRepository {
            get {
                return ResourceManager.GetString("SavingItemInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting all {0} items in the repository..
        /// </summary>
        public static string SelectAllItemsFromRepository {
            get {
                return ResourceManager.GetString("SelectAllItemsFromRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting the first matching {0} in the repository..
        /// </summary>
        public static string SelectFirstMatchingItemFromRepository {
            get {
                return ResourceManager.GetString("SelectFirstMatchingItemFromRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting any matching {0} items in the repository.
        /// </summary>
        public static string SelectMatchingItemsInRepository {
            get {
                return ResourceManager.GetString("SelectMatchingItemsInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating all {0} items in the repository..
        /// </summary>
        public static string UpdateAllItemsInRepository {
            get {
                return ResourceManager.GetString("UpdateAllItemsInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating any matching {0} items in the repository.
        /// </summary>
        public static string UpdateMatchingItemsInRepository {
            get {
                return ResourceManager.GetString("UpdateMatchingItemsInRepository", resourceCulture);
            }
        }
    }
}
