//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Startitecture.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Startitecture.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account &apos;{0}&apos; could not be identified: {1}.
        /// </summary>
        public static string AccountCouldNotBeIdentified {
            get {
                return ResourceManager.GetString("AccountCouldNotBeIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account information provider type was not set in the audit configuration..
        /// </summary>
        public static string AccountInformationProviderTypeConfigurationMissing {
            get {
                return ResourceManager.GetString("AccountInformationProviderTypeConfigurationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action &apos;{0}&apos; could not be initiated..
        /// </summary>
        public static string ActionCouldNotBeInitiated {
            get {
                return ResourceManager.GetString("ActionCouldNotBeInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action identifier &apos;{0}&apos; for action &apos;{1}&apos; could not be found..
        /// </summary>
        public static string ActionIdentifierNotFound {
            get {
                return ResourceManager.GetString("ActionIdentifierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to complete action &apos;{0}&apos; that could not be found..
        /// </summary>
        public static string ActionToCompleteNotFound {
            get {
                return ResourceManager.GetString("ActionToCompleteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t locate assembly &apos;{0}&apos;..
        /// </summary>
        public static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must be decorated with attribute &apos;{1}&apos;..
        /// </summary>
        public static string AttributeRequiredForType {
            get {
                return ResourceManager.GetString("AttributeRequiredForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audit configuration element &apos;{0}&apos; was not found..
        /// </summary>
        public static string AuditConfigurationNotFound {
            get {
                return ResourceManager.GetString("AuditConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to navigate to POCO attribute..
        /// </summary>
        public static string BrokenPocoAttributePath {
            get {
                return ResourceManager.GetString("BrokenPocoAttributePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate &apos;{0}&apos; could not be located in the local machine store..
        /// </summary>
        public static string CertificateNotFound {
            get {
                return ResourceManager.GetString("CertificateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close client for &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ClientProxyCouldNotBeClosed {
            get {
                return ResourceManager.GetString("ClientProxyCouldNotBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command factory is null for POCO data &apos;{0}&apos;..
        /// </summary>
        public static string CommandFactoryReturnedNullCommand {
            get {
                return ResourceManager.GetString("CommandFactoryReturnedNullCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second value must be the same type as the first value..
        /// </summary>
        public static string ComparisonValuesMustBeSameType {
            get {
                return ResourceManager.GetString("ComparisonValuesMustBeSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component &apos;{0}&apos; has been aborted and cannot accept any further requests..
        /// </summary>
        public static string ComponentAbortedAndRefusingRequests {
            get {
                return ResourceManager.GetString("ComponentAbortedAndRefusingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component &apos;{0}&apos; has encountered an unhandled exception and will exit: {1}.
        /// </summary>
        public static string ComponentExitingWithUnhandledError {
            get {
                return ResourceManager.GetString("ComponentExitingWithUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &apos;{0}&apos; failing {1} with error {2} could not be recorded. The original error is:{3}{4}{3}The recording error is:{3}{5}.
        /// </summary>
        public static string ComponentFailureCouldNotBeRecorded {
            get {
                return ResourceManager.GetString("ComponentFailureCouldNotBeRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection factory &apos;{0}&apos; returned a null connection..
        /// </summary>
        public static string ConnectionFactoryReturnedNullConnection {
            get {
                return ResourceManager.GetString("ConnectionFactoryReturnedNullConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find connection type &apos;{0}&apos;. .
        /// </summary>
        public static string ConnectionTypeNotFound {
            get {
                return ResourceManager.GetString("ConnectionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constructor info for the type {0} was null..
        /// </summary>
        public static string ConstructorInfoDoesNotExist {
            get {
                return ResourceManager.GetString("ConstructorInfoDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set primary key {0}.{1} with value &apos;{2}&apos;: {3}.
        /// </summary>
        public static string CouldNotSetPrimaryKeyWithValue {
            get {
                return ResourceManager.GetString("CouldNotSetPrimaryKeyWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current status of the routing request did not contain a current route..
        /// </summary>
        public static string CurrentRouteNotFound {
            get {
                return ResourceManager.GetString("CurrentRouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current status of the message is required for action &apos;{0}&apos;..
        /// </summary>
        public static string CurrentRoutingStatusRequired {
            get {
                return ResourceManager.GetString("CurrentRoutingStatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database context connection must be a SqlConnection..
        /// </summary>
        public static string DatabaseContextConnectionIsNotSqlConnection {
            get {
                return ResourceManager.GetString("DatabaseContextConnectionIsNotSqlConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insertion of {0} &apos;{1}&apos; failed..
        /// </summary>
        public static string DataItemInsertionFailed {
            get {
                return ResourceManager.GetString("DataItemInsertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update of {0} &apos;{1}&apos; affected multiple rows..
        /// </summary>
        public static string DataItemUpdateAffectedMultipleRows {
            get {
                return ResourceManager.GetString("DataItemUpdateAffectedMultipleRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update of {0} &apos;{1}&apos; was not applied..
        /// </summary>
        public static string DataItemUpdateNotApplied {
            get {
                return ResourceManager.GetString("DataItemUpdateNotApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source location must exist..
        /// </summary>
        public static string DataSourceDoesNotExist {
            get {
                return ResourceManager.GetString("DataSourceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source location must be set..
        /// </summary>
        public static string DataSourceLocationNotSet {
            get {
                return ResourceManager.GetString("DataSourceLocationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed routing of &apos;{0}&apos; failed: {1}.
        /// </summary>
        public static string DelayedRoutingError {
            get {
                return ResourceManager.GetString("DelayedRoutingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery of the message was administratively canceled..
        /// </summary>
        public static string DeliveryAdministrativelyCanceled {
            get {
                return ResourceManager.GetString("DeliveryAdministrativelyCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dependency for type &apos;{0}&apos; has not been configured..
        /// </summary>
        public static string DependencyNotConfigured {
            get {
                return ResourceManager.GetString("DependencyNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value at &apos;{0}&apos; was not of type &apos;{1}&apos; (actual: &apos;{2}&apos;)..
        /// </summary>
        public static string DictionaryValueNotOfExpectedType {
            get {
                return ResourceManager.GetString("DictionaryValueNotOfExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No distribution channels are currently available..
        /// </summary>
        public static string DistributionChannelsNotAvailable {
            get {
                return ResourceManager.GetString("DistributionChannelsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic types are not supported with this method..
        /// </summary>
        public static string DynamicTypesNotSupported {
            get {
                return ResourceManager.GetString("DynamicTypesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumeration did not contain the expected number of elements..
        /// </summary>
        public static string EnumerationCountMismatch {
            get {
                return ResourceManager.GetString("EnumerationCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumeration must be set to a known value..
        /// </summary>
        public static string EnumerationMustBeKnownValue {
            get {
                return ResourceManager.GetString("EnumerationMustBeKnownValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start new event &apos;{0}&apos; because the action event failed validation..
        /// </summary>
        public static string EventFailedValidation {
            get {
                return ResourceManager.GetString("EventFailedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start new event &apos;{0}&apos; because the same identifier is in use..
        /// </summary>
        public static string EventIdentifierCollision {
            get {
                return ResourceManager.GetString("EventIdentifierCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event repository has not been configured in the configuration file..
        /// </summary>
        public static string EventRepositoryNotConfigured {
            get {
                return ResourceManager.GetString("EventRepositoryNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified event repository type &apos;{0}&apos; does not exist..
        /// </summary>
        public static string EventRepositoryTypeNotFound {
            get {
                return ResourceManager.GetString("EventRepositoryTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender of event &apos;{0}&apos; was of type {1} (expected {2})..
        /// </summary>
        public static string EventSourceNotOfExpectedType {
            get {
                return ResourceManager.GetString("EventSourceNotOfExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event subscriber of &apos;{0}&apos; threw exception in background thread: {1}.
        /// </summary>
        public static string EventSubscriberThrewExceptionInBackgroundThread {
            get {
                return ResourceManager.GetString("EventSubscriberThrewExceptionInBackgroundThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The failure route for request &apos;{0}&apos; with ID {1} was already removed..
        /// </summary>
        public static string FailureRouteInformationAlreadyRemoved {
            get {
                return ResourceManager.GetString("FailureRouteInformationAlreadyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A FaultContractAttribute was not found on a user-defined operation method..
        /// </summary>
        public static string FaultContractNotSpecified {
            get {
                return ResourceManager.GetString("FaultContractNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save fault &apos;{0}&apos; to the repository: {1}.
        /// </summary>
        public static string FaultRepositoryFailureOnSave {
            get {
                return ResourceManager.GetString("FaultRepositoryFailureOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault &apos;{0}&apos; has already been saved to the repository..
        /// </summary>
        public static string FaultRepositoryFaultAlreadySaved {
            get {
                return ResourceManager.GetString("FaultRepositoryFaultAlreadySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was not found at path &apos;{1}&apos;..
        /// </summary>
        public static string FileNotFoundAtPath {
            get {
                return ResourceManager.GetString("FileNotFoundAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token request returned was null or not an HttpWebRequest..
        /// </summary>
        public static string HttpWebRequestNotReturned {
            get {
                return ResourceManager.GetString("HttpWebRequestNotReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index properties are not supported by this method..
        /// </summary>
        public static string IndexPropertiesNotSupported {
            get {
                return ResourceManager.GetString("IndexPropertiesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A(n) {0} (message: {1}) resulted in the following {2}: {3}.
        /// </summary>
        public static string InnerExceptionMessage {
            get {
                return ResourceManager.GetString("InnerExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item could not be added to the collection..
        /// </summary>
        public static string ItemCouldNotBeAddedToCollection {
            get {
                return ResourceManager.GetString("ItemCouldNotBeAddedToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemSelections of type {0} are not supported..
        /// </summary>
        public static string ItemSelectionTypeNotSupported {
            get {
                return ResourceManager.GetString("ItemSelectionTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key mapping for the same type as the Data Item is not supported..
        /// </summary>
        public static string KeyMappingToDataItemTypeNotSupported {
            get {
                return ResourceManager.GetString("KeyMappingToDataItemTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key mapping for the same type as the Entity is not supported..
        /// </summary>
        public static string KeyMappingToEntityTypeNotSupported {
            get {
                return ResourceManager.GetString("KeyMappingToEntityTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported in the {1} implementation..
        /// </summary>
        public static string KeyTypeNotSupportedForInsert {
            get {
                return ResourceManager.GetString("KeyTypeNotSupportedForInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have matching key property for {1}.{2}.
        /// </summary>
        public static string MatchingKeyPropertyNotFound {
            get {
                return ResourceManager.GetString("MatchingKeyPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery of the message was canceled because a newer message supersedes it..
        /// </summary>
        public static string MessageCanceledByNewerMessage {
            get {
                return ResourceManager.GetString("MessageCanceledByNewerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not finalize &apos;{1}&apos; with ID {2}..
        /// </summary>
        public static string MessageCouldNotBeFinalized {
            get {
                return ResourceManager.GetString("MessageCouldNotBeFinalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message was not accepted by route &apos;{0}&apos;: {1}.
        /// </summary>
        public static string MessageNotAcceptedByRoute {
            get {
                return ResourceManager.GetString("MessageNotAcceptedByRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a message that is already complete..
        /// </summary>
        public static string MessageRequestAlreadyComplete {
            get {
                return ResourceManager.GetString("MessageRequestAlreadyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the remote share..
        /// </summary>
        public static string NetworkShareNotAvailable {
            get {
                return ResourceManager.GetString("NetworkShareNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no property matching the specified relation..
        /// </summary>
        public static string NoMatchingPropertyForRelation {
            get {
                return ResourceManager.GetString("NoMatchingPropertyForRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles were specified..
        /// </summary>
        public static string NoProfilesSpecified {
            get {
                return ResourceManager.GetString("NoProfilesSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No provider is available to save {0} &apos;{1}&apos;..
        /// </summary>
        public static string NoProviderAvailable {
            get {
                return ResourceManager.GetString("NoProviderAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query must alias &apos;*&apos; when performing a paged query (e.g., &apos;select t.* from table t order by t.id&apos;)..
        /// </summary>
        public static string OracleQueryMustAliasForPagedQuery {
            get {
                return ResourceManager.GetString("OracleQueryMustAliasForPagedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse SQL statement for paged query..
        /// </summary>
        public static string PagedSqlCouldNotBeParsed {
            get {
                return ResourceManager.GetString("PagedSqlCouldNotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified postal code string was not in a recognizable format..
        /// </summary>
        public static string PostalCodeInvalidFormat {
            get {
                return ResourceManager.GetString("PostalCodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process &apos;{0}&apos; has been canceled and cannot be started again..
        /// </summary>
        public static string ProcessCanceledAndCannotBeRestarted {
            get {
                return ResourceManager.GetString("ProcessCanceledAndCannotBeRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0}.{1} value {2} is out of range..
        /// </summary>
        public static string PropertyIsOutOfRange {
            get {
                return ResourceManager.GetString("PropertyIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property&apos;s name was not set..
        /// </summary>
        public static string PropertyNameNotSet {
            get {
                return ResourceManager.GetString("PropertyNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is not set and cannot be written from {1} &apos;{2}&apos;..
        /// </summary>
        public static string ReadOnlyPropertyCannotBeWrittenTo {
            get {
                return ResourceManager.GetString("ReadOnlyPropertyCannotBeWrittenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; could not be located by configuration settings, relative search path or executing assembly..
        /// </summary>
        public static string RelativeFileCouldNotBeFound {
            get {
                return ResourceManager.GetString("RelativeFileCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependent {0} item &apos;{1}&apos; does not exist in the repository..
        /// </summary>
        public static string RepositoryDependencyDoesNotExist {
            get {
                return ResourceManager.GetString("RepositoryDependencyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider is disposed and cannot be used as a transaction provider..
        /// </summary>
        public static string RepositoryProviderIsDisposed {
            get {
                return ResourceManager.GetString("RepositoryProviderIsDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request &apos;{0}&apos; with ID {1} could not be found in router {2}..
        /// </summary>
        public static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result &apos;{0}&apos; type &apos;{1}&apos; is not supported..
        /// </summary>
        public static string ResultTypeNotSupported {
            get {
                return ResourceManager.GetString("ResultTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The routing request did not contain a routing configuration..
        /// </summary>
        public static string RoutingConfigurationNotFound {
            get {
                return ResourceManager.GetString("RoutingConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The routing information for request &apos;{0}&apos; with ID {1} was already removed..
        /// </summary>
        public static string RoutingInformationAlreadyRemoved {
            get {
                return ResourceManager.GetString("RoutingInformationAlreadyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The routing request did not contain a notification..
        /// </summary>
        public static string RoutingNotificationNotFound {
            get {
                return ResourceManager.GetString("RoutingNotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save event &apos;{0}&apos;: {1}.
        /// </summary>
        public static string SaveEventFailed {
            get {
                return ResourceManager.GetString("SaveEventFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The separated values stream is not in the proper format..
        /// </summary>
        public static string SeparatedValuesFileNotInProperFormat {
            get {
                return ResourceManager.GetString("SeparatedValuesFileNotInProperFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service configuration with the name &apos;{0}&apos; was not found..
        /// </summary>
        public static string ServiceConfigurationNotFound {
            get {
                return ResourceManager.GetString("ServiceConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service elements have been loaded..
        /// </summary>
        public static string ServiceElementsNotLoaded {
            get {
                return ResourceManager.GetString("ServiceElementsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service status with ID &apos;{0}&apos; for configuration &apos;{1}&apos; could not be found..
        /// </summary>
        public static string ServiceRequestStatusNotFound {
            get {
                return ResourceManager.GetString("ServiceRequestStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove &apos;{0}&apos; from the sorted set..
        /// </summary>
        public static string SortedSetItemNotFoundForRemoval {
            get {
                return ResourceManager.GetString("SortedSetItemNotFoundForRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path &apos;{0}&apos; does not exist..
        /// </summary>
        public static string SourcePathDoesNotExist {
            get {
                return ResourceManager.GetString("SourcePathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cancel a process when it is not running..
        /// </summary>
        public static string StoppedProcessCannotBeCanceled {
            get {
                return ResourceManager.GetString("StoppedProcessCannotBeCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is not supported..
        /// </summary>
        public static string TokenRequestNotSupported {
            get {
                return ResourceManager.GetString("TokenRequestNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was not valid for the specified protocol..
        /// </summary>
        public static string TokenRequestProtocolViolation {
            get {
                return ResourceManager.GetString("TokenRequestProtocolViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote server responded with the following status: {0} [code: {1}].
        /// </summary>
        public static string TokenRequestWebException {
            get {
                return ResourceManager.GetString("TokenRequestWebException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item&apos;s transaction context was not set..
        /// </summary>
        public static string TransactionContextNotSet {
            get {
                return ResourceManager.GetString("TransactionContextNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load type &apos;{0}&apos;: assembly name needed and no assembly name specified..
        /// </summary>
        public static string TypeCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("TypeCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set {0}.{1} to &apos;{2}&apos;: {3}.
        /// </summary>
        public static string UnableToSetPropertyToValue {
            get {
                return ResourceManager.GetString("UnableToSetPropertyToValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} requests were removed by their ID..
        /// </summary>
        public static string UnexpectedNumberOfRequestsRemoved {
            get {
                return ResourceManager.GetString("UnexpectedNumberOfRequestsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error processing message delivery for &apos;{0}&apos;: {1}.
        /// </summary>
        public static string UnhandledExceptionDuringMessageDelivery {
            get {
                return ResourceManager.GetString("UnhandledExceptionDuringMessageDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller&apos;s {0} method threw an exception: {1}.
        /// </summary>
        public static string UnhandledExceptionFromCallerMethod {
            get {
                return ResourceManager.GetString("UnhandledExceptionFromCallerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or whitespace..
        /// </summary>
        public static string ValueCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML stream could not be deserialized..
        /// </summary>
        public static string XmlCouldNotBeDeserialized {
            get {
                return ResourceManager.GetString("XmlCouldNotBeDeserialized", resourceCulture);
            }
        }
    }
}
