//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAF.StringResources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action &apos;{0}&apos; is not supported for this method..
        /// </summary>
        public static string ActionIsNotSupportedForMethod {
            get {
                return ResourceManager.GetString("ActionIsNotSupportedForMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load types from assembly &apos;{0}&apos;: {1}.
        /// </summary>
        public static string AssemblyTypesCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("AssemblyTypesCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one element must be contained in the collection.
        /// </summary>
        public static string CollectionRequiresOneOrMoreElements {
            get {
                return ResourceManager.GetString("CollectionRequiresOneOrMoreElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The completion time must be equal to or greater than the initiation time..
        /// </summary>
        public static string CompletionTimeEarlierThanInitiationTime {
            get {
                return ResourceManager.GetString("CompletionTimeEarlierThanInitiationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource monitor &apos;{0}&apos; cannot be added because the component monitor is already initialized..
        /// </summary>
        public static string ComponentMonitorAlreadyInitialized {
            get {
                return ResourceManager.GetString("ComponentMonitorAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string did not specify a provider..
        /// </summary>
        public static string ConnectionStringDidNotSpecifyProvider {
            get {
                return ResourceManager.GetString("ConnectionStringDidNotSpecifyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified connection string could not be found..
        /// </summary>
        public static string ConnectionStringNameNotFound {
            get {
                return ResourceManager.GetString("ConnectionStringNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified provider does not exist..
        /// </summary>
        public static string ConnectionStringProviderDoesNotExist {
            get {
                return ResourceManager.GetString("ConnectionStringProviderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and destination directories cannot be the same..
        /// </summary>
        public static string CopyDirectorySourceAndDestinationAreSame {
            get {
                return ResourceManager.GetString("CopyDirectorySourceAndDestinationAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The factory did not create a new connection..
        /// </summary>
        public static string DataConnectionFactoryReturnedNull {
            get {
                return ResourceManager.GetString("DataConnectionFactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery has already completed..
        /// </summary>
        public static string DeliveryAlreadyCompleted {
            get {
                return ResourceManager.GetString("DeliveryAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dependency profile that maps to the same type as the entity will create an infinite loop..
        /// </summary>
        public static string DependencyMappingToSameTypeAsEntity {
            get {
                return ResourceManager.GetString("DependencyMappingToSameTypeAsEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination path cannot be the same as the source path..
        /// </summary>
        public static string DestinationPathSameAsSourcePath {
            get {
                return ResourceManager.GetString("DestinationPathSameAsSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property {1} was not set..
        /// </summary>
        public static string EntityDependencyCheckFailed {
            get {
                return ResourceManager.GetString("EntityDependencyCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one property must be specified that matches the entity type..
        /// </summary>
        public static string EntityPropertyMatchRequired {
            get {
                return ResourceManager.GetString("EntityPropertyMatchRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; property &apos;{2}&apos; [&apos;{3}&apos;] failed one or more validation checks: {4}.
        /// </summary>
        public static string EntityPropertyValidationFailed {
            get {
                return ResourceManager.GetString("EntityPropertyValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; failed validation check &apos;{2}&apos;..
        /// </summary>
        public static string EntityValidationCheckFailed {
            get {
                return ResourceManager.GetString("EntityValidationCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; failed one or more validation checks: {2}.
        /// </summary>
        public static string EntityValidationFailed {
            get {
                return ResourceManager.GetString("EntityValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item failed the validation check. The first of {0} failures was: {1}.
        /// </summary>
        public static string EntityValidationFailedMultiple {
            get {
                return ResourceManager.GetString("EntityValidationFailedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item failed a validation check: {0}.
        /// </summary>
        public static string EntityValidationFailedSingle {
            get {
                return ResourceManager.GetString("EntityValidationFailedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape format must contain a single string placeholder (&apos;{0}&apos;)..
        /// </summary>
        public static string EscapeMaskInvalidFormat {
            get {
                return ResourceManager.GetString("EscapeMaskInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A failure route was not specified.
        /// </summary>
        public static string FailureRouteNotSpecified {
            get {
                return ResourceManager.GetString("FailureRouteNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create generic type for &apos;{0}&apos; with generic arguments &apos;{1}&apos;: {2}.
        /// </summary>
        public static string GenericTypeCouldNotBeCreated {
            get {
                return ResourceManager.GetString("GenericTypeCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be set..
        /// </summary>
        public static string ItemMustBeSet {
            get {
                return ResourceManager.GetString("ItemMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; value &apos;{1}&apos; failed validation: {2}.
        /// </summary>
        public static string ItemValidationFailed {
            get {
                return ResourceManager.GetString("ItemValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum queue count must be greater than zero..
        /// </summary>
        public static string MaxQueueCountLessThanOne {
            get {
                return ResourceManager.GetString("MaxQueueCountLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has already been delivered and cannot be canceled..
        /// </summary>
        public static string MessageAlreadyDelivered {
            get {
                return ResourceManager.GetString("MessageAlreadyDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has already been sent..
        /// </summary>
        public static string MessageAlreadySent {
            get {
                return ResourceManager.GetString("MessageAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message has not been delivered..
        /// </summary>
        public static string MessageNotDelivered {
            get {
                return ResourceManager.GetString("MessageNotDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified message was not saved by the profile provider..
        /// </summary>
        public static string MessageNotSaved {
            get {
                return ResourceManager.GetString("MessageNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fail a message request without an error..
        /// </summary>
        public static string MessageRequestCannotBeFailedWithoutError {
            get {
                return ResourceManager.GetString("MessageRequestCannotBeFailedWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum queue count must be equal to or greater than the minimum queue count..
        /// </summary>
        public static string MinQueueCountGreaterThanMaxQueueCount {
            get {
                return ResourceManager.GetString("MinQueueCountGreaterThanMaxQueueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum queue count must be one or greater..
        /// </summary>
        public static string MinQueueCountLessThanOne {
            get {
                return ResourceManager.GetString("MinQueueCountLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map item to non-existent named column&apos;{0}&apos;..
        /// </summary>
        public static string NamedColumnCannotBeMapped {
            get {
                return ResourceManager.GetString("NamedColumnCannotBeMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one distribution channel is required..
        /// </summary>
        public static string NoDistributionChannelsSpecified {
            get {
                return ResourceManager.GetString("NoDistributionChannelsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified property {0}.{1} cannot be mapped by convention because the source is nullable but the target is not. Use MapEntityProperty() instead..
        /// </summary>
        public static string NullablePropertyCannotBeMappedByConvention {
            get {
                return ResourceManager.GetString("NullablePropertyCannotBeMappedByConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of values ({0}) is not supported..
        /// </summary>
        public static string NumberOfValuesNotSupported {
            get {
                return ResourceManager.GetString("NumberOfValuesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the provided paths was not valid..
        /// </summary>
        public static string OneOfMultiplePathsNotValid {
            get {
                return ResourceManager.GetString("OneOfMultiplePathsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be of type &apos;{0}&apos;..
        /// </summary>
        public static string ParameterMustBeOfType {
            get {
                return ResourceManager.GetString("ParameterMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; was not a valid path..
        /// </summary>
        public static string PathWasNotValid {
            get {
                return ResourceManager.GetString("PathWasNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pending request could not be found..
        /// </summary>
        public static string PendingRequestCouldNotBeFound {
            get {
                return ResourceManager.GetString("PendingRequestCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key not set and no alternate keys defined..
        /// </summary>
        public static string PrimaryKeyNotSetAndAlternateKeysNotDefined {
            get {
                return ResourceManager.GetString("PrimaryKeyNotSetAndAlternateKeysNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified property could not be mapped by convention: the expected property name was not found..
        /// </summary>
        public static string PropertyMappingNotFoundByConvention {
            get {
                return ResourceManager.GetString("PropertyMappingNotFoundByConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; must be set..
        /// </summary>
        public static string PropertyMustBeSet {
            get {
                return ResourceManager.GetString("PropertyMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property must have a declaring type..
        /// </summary>
        public static string PropertyMustHaveDeclaringType {
            get {
                return ResourceManager.GetString("PropertyMustHaveDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; value &apos;{1}&apos; failed validation &apos;{2}&apos;..
        /// </summary>
        public static string PropertyValidationFailed {
            get {
                return ResourceManager.GetString("PropertyValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; value &apos;{1}&apos; is not in a valid format..
        /// </summary>
        public static string PropertyValueIsInvalidFormat {
            get {
                return ResourceManager.GetString("PropertyValueIsInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; value &apos;{1}&apos; could not be converted to type &apos;{2}&apos;..
        /// </summary>
        public static string PropertyValueNotConvertable {
            get {
                return ResourceManager.GetString("PropertyValueNotConvertable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; value &apos;{1}&apos; is not between &apos;{2}&apos; and &apos;{3}&apos;..
        /// </summary>
        public static string PropertyValueOutOfRange {
            get {
                return ResourceManager.GetString("PropertyValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request &apos;{0}&apos; with ID {1} is already active in the current router..
        /// </summary>
        public static string RequestAlreadyActive {
            get {
                return ResourceManager.GetString("RequestAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The routing profile &apos;{0}&apos; contained a null service route..
        /// </summary>
        public static string RoutingProfileContainedNullRoute {
            get {
                return ResourceManager.GetString("RoutingProfileContainedNullRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route &apos;{0}&apos; is not contained within the specified profile..
        /// </summary>
        public static string RoutingProfileDidNotContainRoute {
            get {
                return ResourceManager.GetString("RoutingProfileDidNotContainRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profile was found for message &apos;{0}&apos;..
        /// </summary>
        public static string RoutingProfileNotFoundForMessage {
            get {
                return ResourceManager.GetString("RoutingProfileNotFoundForMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the profiles can be null..
        /// </summary>
        public static string RoutingProfileWasNull {
            get {
                return ResourceManager.GetString("RoutingProfileWasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current routing status must be set..
        /// </summary>
        public static string RoutingStatusNotSet {
            get {
                return ResourceManager.GetString("RoutingStatusNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service route for the current status must be set..
        /// </summary>
        public static string RoutingStatusRouteNotSet {
            get {
                return ResourceManager.GetString("RoutingStatusRouteNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save operation did not return the item &apos;{0}&apos;..
        /// </summary>
        public static string SaveOperationDidNotReturnItem {
            get {
                return ResourceManager.GetString("SaveOperationDidNotReturnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector cannot be evaluated..
        /// </summary>
        public static string SelectorCannotBeEvaluated {
            get {
                return ResourceManager.GetString("SelectorCannotBeEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service routes were specified..
        /// </summary>
        public static string ServiceRoutesNotSpecified {
            get {
                return ResourceManager.GetString("ServiceRoutesNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route type was not found in the queue pool provider..
        /// </summary>
        public static string ServiceRouteTypeNotFound {
            get {
                return ResourceManager.GetString("ServiceRouteTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source path &apos;{0}&apos; is equal to destination path &apos;{1}&apos;..
        /// </summary>
        public static string SourcePathEqualToDestinationPath {
            get {
                return ResourceManager.GetString("SourcePathEqualToDestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one parameter must be specified..
        /// </summary>
        public static string SpecifyAtLeastOneParameter {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;@{0}&apos; specified but none of the passed arguments have a property with this name (in &apos;{1}&apos;)..
        /// </summary>
        public static string SqlParameterDoesNotMatchArguments {
            get {
                return ResourceManager.GetString("SqlParameterDoesNotMatchArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;@{0}&apos; specified but only {1} parameters supplied (in `{2}`)..
        /// </summary>
        public static string SqlParameterHasNoMatchingValue {
            get {
                return ResourceManager.GetString("SqlParameterHasNoMatchingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The statement is not a valid SELECT statement..
        /// </summary>
        public static string SqlStatementIsNotSelectStatement {
            get {
                return ResourceManager.GetString("SqlStatementIsNotSelectStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the value of static property &apos;{0}&apos; on type &apos;{1}&apos;: {2}.
        /// </summary>
        public static string StaticPropertyValueCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("StaticPropertyValueCouldNotBeRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A target item must be specified for action &apos;{0}&apos;..
        /// </summary>
        public static string TargetRequiredForAction {
            get {
                return ResourceManager.GetString("TargetRequiredForAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not contain property &apos;{1}&apos;..
        /// </summary>
        public static string TypeDoesNotContainProperty {
            get {
                return ResourceManager.GetString("TypeDoesNotContainProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not have a default constructor..
        /// </summary>
        public static string TypeDoesNotHaveDefaultConstructor {
            get {
                return ResourceManager.GetString("TypeDoesNotHaveDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not implement the required interface &apos;{1}&apos;..
        /// </summary>
        public static string TypeDoesNotImplementRequiredInterface {
            get {
                return ResourceManager.GetString("TypeDoesNotImplementRequiredInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not an instance of &apos;{1}&apos;..
        /// </summary>
        public static string TypeIsNotInstanceOfExpectedType {
            get {
                return ResourceManager.GetString("TypeIsNotInstanceOfExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation state for property &apos;{0}&apos; value &apos;{1}&apos; is unknown..
        /// </summary>
        public static string UnknownValidationState {
            get {
                return ResourceManager.GetString("UnknownValidationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset property &apos;{0}&apos; is empty and should be null..
        /// </summary>
        public static string UnsetPropertyShouldBeNull {
            get {
                return ResourceManager.GetString("UnsetPropertyShouldBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No properties could be updated with the specified selection..
        /// </summary>
        public static string UpdateSelectionHadNoTargetProperties {
            get {
                return ResourceManager.GetString("UpdateSelectionHadNoTargetProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account &apos;{0}&apos; could not be located by the {1}..
        /// </summary>
        public static string UserAccountNotFoundByProvider {
            get {
                return ResourceManager.GetString("UserAccountNotFoundByProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account cannot be null..
        /// </summary>
        public static string UserAccountNotSet {
            get {
                return ResourceManager.GetString("UserAccountNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} and {1} inclusive..
        /// </summary>
        public static string ValueMustBeBetweenInclusive {
            get {
                return ResourceManager.GetString("ValueMustBeBetweenInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than zero..
        /// </summary>
        public static string ValueMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than or equal to zero..
        /// </summary>
        public static string ValueMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("ValueMustBeZeroOrGreater", resourceCulture);
            }
        }
    }
}
