// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Workflow
{
    using Startitecture.Orm.Common;
    using System.Diagnostics.CodeAnalysis;

    using Startitecture.Orm.Schema;

    /// <summary>
    /// The Attachment entity POCO.
    /// </summary>
    [Table("Attachment", Schema = "workflow")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class AttachmentRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AttachmentRow"/> class.
        /// </summary>
        public AttachmentRow()
        {
        }

        /// <summary>
        /// Gets or sets the AttachmentId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"AttachmentId", Order = 1, TypeName = "bigint")]
        [Index(@"PK_Attachment", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Attachment ID")]
        public long AttachmentId { get; set; }

        /// <summary>
        /// Gets or sets the WorkflowFormSubmissionId
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"WorkflowFormSubmissionId", Order = 2, TypeName = "bigint")]
        [Required]
        [Display(Name = "Workflow form submission ID")]
        public long WorkflowFormSubmissionId { get; set; }

        /// <summary>
        /// Gets or sets the Subject (length: 100)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Subject", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Subject")]
        public string Subject { get; set; }

        /// <summary>
        /// Gets or sets the Order
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Order", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Order")]
        public int Order { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent WorkflowFormSubmission pointed by [Attachment].([WorkflowFormSubmissionId]) (FK_Attachment_WorkflowFormSubmission)
        /// </summary>
        [ForeignKey("WorkflowFormSubmissionId")] public WorkflowFormSubmissionRow WorkflowFormSubmission { get; set; } // FK_Attachment_WorkflowFormSubmission
    }

}
// </auto-generated>
