// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities
{
    using Startitecture.Orm.Common;
    using Startitecture.Orm.Schema;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The Container entity POCO.
    /// </summary>
    [Table("Container", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class ContainerRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContainerRow"/> class.
        /// </summary>
        public ContainerRow()
        {
        }

        /// <summary>
        /// Gets or sets the ContainerId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"ContainerId", Order = 1, TypeName = "int")]
        [Index(@"PK_Container", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Container ID")]
        public int ContainerId { get; set; }

        /// <summary>
        /// Gets or sets the Name (length: 260)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Name", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(260)]
        [StringLength(260)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Path (length: 260)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Path", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(260)]
        [StringLength(260)]
        [Display(Name = "Path")]
        public string Path { get; set; }
    }

}
// </auto-generated>
