// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Forms
{
    using Startitecture.Orm.Schema;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The CurrencyValueItem entity POCO.
    /// </summary>
    [Table("CurrencyValueItem", Schema = "forms")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class CurrencyValueItemRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrencyValueItemRow"/> class.
        /// </summary>
        public CurrencyValueItemRow()
        {
        }

        /// <summary>
        /// Gets or sets the CurrencyValueItemId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"CurrencyValueItemId", Order = 1, TypeName = "bigint")]
        [Index(@"PK_CurrencyValueItem", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Currency value item ID")]
        [ForeignKey("FieldValueItem")]
        public long CurrencyValueItemId { get; set; }

        /// <summary>
        /// Gets or sets the Value
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Value", Order = 2, TypeName = "decimal")]
        [Required]
        [Display(Name = "Value")]
        public decimal Value { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent FieldValueItem pointed by [CurrencyValueItem].([CurrencyValueItemId]) (FK_CurrencyValueItem_FieldValueItem)
        /// </summary>
        [ForeignKey("CurrencyValueItemId")] public FieldValueItemRow FieldValueItem { get; set; } // FK_CurrencyValueItem_FieldValueItem
    }

}
// </auto-generated>
