// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities
{
    using Startitecture.Orm.Schema;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The DocumentVersion entity POCO.
    /// </summary>
    [Table("DocumentVersion", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class DocumentVersionRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentVersionRow"/> class.
        /// </summary>
        public DocumentVersionRow()
        {
        }

        /// <summary>
        /// Gets or sets the DocumentVersionId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"DocumentVersionId", Order = 1, TypeName = "int")]
        [Index(@"PK_DocumentVersion", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Document version ID")]
        public int DocumentVersionId { get; set; }

        /// <summary>
        /// Gets or sets the DocumentId
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"DocumentId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Document ID")]
        public int DocumentId { get; set; }

        /// <summary>
        /// Gets or sets the FileName (length: 260)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"FileName", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(260)]
        [StringLength(260)]
        [Display(Name = "File name")]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or sets the Uri (length: 260)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Uri", Order = 4, TypeName = "nvarchar")]
        [Index(@"UK_DocumentVersion_Uri", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [MaxLength(260)]
        [StringLength(260)]
        [Display(Name = "Uri")]
        public string Uri { get; set; }

        /// <summary>
        /// Gets or sets the Revision
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Revision", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Revision")]
        public int Revision { get; set; }

        /// <summary>
        /// Gets or sets the RevisionTime
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"RevisionTime", Order = 6, TypeName = "datetimeoffset")]
        [Required]
        [Display(Name = "Revision time")]
        public System.DateTimeOffset RevisionTime { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent Document pointed by [DocumentVersion].([DocumentId]) (FK_DocumentVersion_Document)
        /// </summary>
        [ForeignKey("DocumentId")] public DocumentRow Document { get; set; } // FK_DocumentVersion_Document
    }

}
// </auto-generated>
