// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities
{
    using Startitecture.Orm.Schema;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The Document entity POCO.
    /// </summary>
    [Table("Document", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class DocumentRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentRow"/> class.
        /// </summary>
        public DocumentRow()
        {
        }

        /// <summary>
        /// Gets or sets the DocumentId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"DocumentId", Order = 1, TypeName = "int")]
        [Index(@"PK_Document", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Document ID")]
        public int DocumentId { get; set; }

        /// <summary>
        /// Gets or sets the ContainerId
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"ContainerId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Container ID")]
        public int ContainerId { get; set; }

        /// <summary>
        /// Gets or sets the ResourceClassificationId
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"ResourceClassificationId", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Resource classification ID")]
        public int ResourceClassificationId { get; set; }

        /// <summary>
        /// Gets or sets the Name (length: 260)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Name", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(260)]
        [StringLength(260)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent Container pointed by [Document].([ContainerId]) (FK_Document_Container)
        /// </summary>
        [ForeignKey("ContainerId")] public ContainerRow Container { get; set; } // FK_Document_Container

        /// <summary>
        /// Gets or sets the Parent ResourceClassification pointed by [Document].([ResourceClassificationId]) (FK_Document_ResourceClassification)
        /// </summary>
        [ForeignKey("ResourceClassificationId")] public ResourceClassificationRow ResourceClassification { get; set; } // FK_Document_ResourceClassification
    }

}
// </auto-generated>
