// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Forms
{
    using Startitecture.Orm.Common;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The DocumentValueItem entity POCO.
    /// </summary>
    [Table("DocumentValueItem", Schema = "forms")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class DocumentValueItemRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentValueItemRow"/> class.
        /// </summary>
        public DocumentValueItemRow()
        {
        }

        /// <summary>
        /// Gets or sets the DocumentValueItemId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"DocumentValueItemId", Order = 1, TypeName = "bigint")]
        [Index(@"PK_DocumentValueItem", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Document value item ID")]
        [ForeignKey("FieldValueItem")]
        public long DocumentValueItemId { get; set; }

        /// <summary>
        /// Gets or sets the DocumentVersionId
        /// </summary>
        [Column(@"DocumentVersionId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Document version ID")]
        public int DocumentVersionId { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent FieldValueItem pointed by [DocumentValueItem].([DocumentValueItemId]) (FK_DocumentValueItem_FieldValueItem)
        /// </summary>
        [ForeignKey("DocumentValueItemId")] public FieldValueItemRow FieldValueItem { get; set; } // FK_DocumentValueItem_FieldValueItem
    }

}
// </auto-generated>
