// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Workflow
{
    using Startitecture.Orm.Common;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The DocumentAttachment entity POCO.
    /// </summary>
    [Table("DocumentAttachment", Schema = "workflow")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class DocumentAttachmentRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentAttachmentRow"/> class.
        /// </summary>
        public DocumentAttachmentRow()
        {
        }

        /// <summary>
        /// Gets or sets the DocumentAttachmentId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"DocumentAttachmentId", Order = 1, TypeName = "bigint")]
        [Index(@"PK_DocumentAttachment", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Document attachment ID")]
        [ForeignKey("Attachment")]
        public long DocumentAttachmentId { get; set; }

        /// <summary>
        /// Gets or sets the DocumentVersionId
        /// </summary>
        [Column(@"DocumentVersionId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Document version ID")]
        public int DocumentVersionId { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent Attachment pointed by [DocumentAttachment].([DocumentAttachmentId]) (FK_DocumentAttachment_Attachment)
        /// </summary>
        [ForeignKey("DocumentAttachmentId")] public AttachmentRow Attachment { get; set; } // FK_DocumentAttachment_Attachment
    }

}
// </auto-generated>
