// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities
{
    using Startitecture.Orm.Common;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The ExternalResource entity POCO.
    /// </summary>
    [Table("ExternalResource", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class ExternalResourceRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalResourceRow"/> class.
        /// </summary>
        public ExternalResourceRow()
        {
        }

        /// <summary>
        /// Gets or sets the ExternalResourceId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ExternalResourceId", Order = 1, TypeName = "int")]
        [Index(@"PK_ExternalResource", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "External resource ID")]
        public int ExternalResourceId { get; set; }

        /// <summary>
        /// Gets or sets the ResourceClassificationId
        /// </summary>
        [Column(@"ResourceClassificationId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Resource classification ID")]
        public int ResourceClassificationId { get; set; }

        /// <summary>
        /// Gets or sets the Name (length: 260)
        /// </summary>
        [Column(@"Name", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(260)]
        [StringLength(260)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Uri (length: 260)
        /// </summary>
        [Column(@"Uri", Order = 4, TypeName = "nvarchar")]
        [Index(@"UK_ExternalResource_Uri", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [MaxLength(260)]
        [StringLength(260)]
        [Display(Name = "Uri")]
        public string Uri { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent ResourceClassification pointed by [ExternalResource].([ResourceClassificationId]) (FK_ExternalResource_ResourceClassification)
        /// </summary>
        [ForeignKey("ResourceClassificationId")] public ResourceClassificationRow ResourceClassification { get; set; } // FK_ExternalResource_ResourceClassification
    }

}
// </auto-generated>
