// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Forms
{
    using Startitecture.Orm.Common;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The FieldPlacement entity POCO.
    /// </summary>
    [Table("FieldPlacement", Schema = "forms")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class FieldPlacementRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldPlacementRow"/> class.
        /// </summary>
        public FieldPlacementRow()
        {
        }

        /// <summary>
        /// Gets or sets the FieldPlacementId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"FieldPlacementId", Order = 1, TypeName = "bigint")]
        [Index(@"PK_FieldPlacement", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Field placement ID")]
        public long FieldPlacementId { get; set; }

        /// <summary>
        /// Gets or sets the FieldInstanceId
        /// </summary>
        [Column(@"FieldInstanceId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Field instance ID")]
        public int FieldInstanceId { get; set; }

        /// <summary>
        /// Gets or sets the LayoutAreaId
        /// </summary>
        [Column(@"LayoutAreaId", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Layout area ID")]
        public int LayoutAreaId { get; set; }

        /// <summary>
        /// Gets or sets the Order
        /// </summary>
        [Column(@"Order", Order = 4, TypeName = "smallint")]
        [Required]
        [Display(Name = "Order")]
        public short Order { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent FieldInstance pointed by [FieldPlacement].([FieldInstanceId]) (FK_FieldPlacement_FieldInstance)
        /// </summary>
        [ForeignKey("FieldInstanceId")] public FieldInstanceRow FieldInstance { get; set; } // FK_FieldPlacement_FieldInstance

        /// <summary>
        /// Gets or sets the Parent LayoutArea pointed by [FieldPlacement].([LayoutAreaId]) (FK_FieldPlacement_LayoutArea)
        /// </summary>
        [ForeignKey("LayoutAreaId")] public LayoutAreaRow LayoutArea { get; set; } // FK_FieldPlacement_LayoutArea
    }

}
// </auto-generated>
