// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Forms
{
    using Startitecture.Orm.Schema;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The FieldValueItem entity POCO.
    /// </summary>
    [Table("FieldValueItem", Schema = "forms")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class FieldValueItemRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldValueItemRow"/> class.
        /// </summary>
        public FieldValueItemRow()
        {
        }

        /// <summary>
        /// Gets or sets the FieldValueItemId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"FieldValueItemId", Order = 1, TypeName = "bigint")]
        [Index(@"PK_FieldValueItem", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Field value item ID")]
        public long FieldValueItemId { get; set; }

        /// <summary>
        /// Gets or sets the FieldValueId
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"FieldValueId", Order = 2, TypeName = "bigint")]
        [Required]
        [Display(Name = "Field value ID")]
        public long FieldValueId { get; set; }

        /// <summary>
        /// Gets or sets the Order
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Order", Order = 3, TypeName = "smallint")]
        [Required]
        [Display(Name = "Order")]
        public short Order { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent FieldValue pointed by [FieldValueItem].([FieldValueId]) (FK_FieldValueItem_FieldValue)
        /// </summary>
        [ForeignKey("FieldValueId")] public FieldValueRow FieldValue { get; set; } // FK_FieldValueItem_FieldValue
    }

}
// </auto-generated>
