// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Forms
{
    using Startitecture.Orm.Common;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The Field entity POCO.
    /// </summary>
    [Table("Field", Schema = "forms")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class FieldRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldRow"/> class.
        /// </summary>
        public FieldRow()
        {
        }

        /// <summary>
        /// Gets or sets the FieldId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"FieldId", Order = 1, TypeName = "int")]
        [Index(@"PK_Field", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Field ID")]
        public int FieldId { get; set; }

        /// <summary>
        /// Gets or sets the DataSliceId
        /// </summary>
        [Column(@"DataSliceId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Data slice ID")]
        public int DataSliceId { get; set; }

        /// <summary>
        /// Gets or sets the FieldTypeId
        /// </summary>
        [Column(@"FieldTypeId", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Field type ID")]
        public int FieldTypeId { get; set; }

        /// <summary>
        /// Gets or sets the ValueTypeId
        /// </summary>
        [Column(@"ValueTypeId", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Value type ID")]
        public int ValueTypeId { get; set; }

        /// <summary>
        /// Gets or sets the Name (length: 50)
        /// </summary>
        [Column(@"Name", Order = 5, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Label
        /// </summary>
        [Column(@"Label", Order = 6, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Label")]
        public string Label { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent FieldType pointed by [Field].([FieldTypeId]) (FK_Field_FieldType)
        /// </summary>
        [ForeignKey("FieldTypeId")] public FieldTypeRow FieldType { get; set; } // FK_Field_FieldType

        /// <summary>
        /// Gets or sets the Parent ValueType pointed by [Field].([ValueTypeId]) (FK_Field_ValueType)
        /// </summary>
        [ForeignKey("ValueTypeId")] public ValueTypeRow ValueType { get; set; } // FK_Field_ValueType
    }

}
// </auto-generated>
