// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Forms
{
    using Startitecture.Orm.Common;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The Form entity POCO.
    /// </summary>
    [Table("Form", Schema = "forms")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class FormRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FormRow"/> class.
        /// </summary>
        public FormRow()
        {
        }

        /// <summary>
        /// Gets or sets the FormId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"FormId", Order = 1, TypeName = "int")]
        [Index(@"PK_Form", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Form ID")]
        public int FormId { get; set; }

        /// <summary>
        /// Gets or sets the Name (length: 50)
        /// </summary>
        [Column(@"Name", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the IsActive
        /// </summary>
        [Column(@"IsActive", Order = 3, TypeName = "bit")]
        [Required]
        [Display(Name = "Is active")]
        public bool IsActive { get; set; }
    }

}
// </auto-generated>
