// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Workflow
{
    using Startitecture.Orm.Common;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The FormPhaseInstance entity POCO.
    /// </summary>
    [Table("FormPhaseInstance", Schema = "workflow")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class FormPhaseInstanceRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FormPhaseInstanceRow"/> class.
        /// </summary>
        public FormPhaseInstanceRow()
        {
        }

        /// <summary>
        /// Gets or sets the FormPhaseInstanceId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"FormPhaseInstanceId", Order = 1, TypeName = "int")]
        [Index(@"PK_FormPhaseInstance", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Form phase instance ID")]
        public int FormPhaseInstanceId { get; set; }

        /// <summary>
        /// Gets or sets the FormVersionId
        /// </summary>
        [Column(@"FormVersionId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Form version ID")]
        public int FormVersionId { get; set; }

        /// <summary>
        /// Gets or sets the ProcessPhaseId
        /// </summary>
        [Column(@"ProcessPhaseId", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Process phase ID")]
        public int ProcessPhaseId { get; set; }

        /// <summary>
        /// Gets or sets the Order
        /// </summary>
        [Column(@"Order", Order = 4, TypeName = "smallint")]
        [Required]
        [Display(Name = "Order")]
        public short Order { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent ProcessPhase pointed by [FormPhaseInstance].([ProcessPhaseId]) (FK_FormPhaseInstance_ProcessPhase)
        /// </summary>
        [ForeignKey("ProcessPhaseId")] public ProcessPhaseRow ProcessPhase { get; set; } // FK_FormPhaseInstance_ProcessPhase
    }

}
// </auto-generated>
