// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Forms
{
    using Startitecture.Orm.Common;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The Page entity POCO.
    /// </summary>
    [Table("Page", Schema = "forms")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class PageRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PageRow"/> class.
        /// </summary>
        public PageRow()
        {
        }

        /// <summary>
        /// Gets or sets the PageId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"PageId", Order = 1, TypeName = "int")]
        [Index(@"PK_Page", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Page ID")]
        public int PageId { get; set; }

        /// <summary>
        /// Gets or sets the FormVersionId
        /// </summary>
        [Column(@"FormVersionId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Form version ID")]
        public int FormVersionId { get; set; }

        /// <summary>
        /// Gets or sets the Name (length: 50)
        /// </summary>
        [Column(@"Name", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Order
        /// </summary>
        [Column(@"Order", Order = 4, TypeName = "smallint")]
        [Required]
        [Display(Name = "Order")]
        public short Order { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent FormVersion pointed by [Page].([FormVersionId]) (FK_Page_FormVersion)
        /// </summary>
        [ForeignKey("FormVersionId")] public FormVersionRow FormVersion { get; set; } // FK_Page_FormVersion
    }

}
// </auto-generated>
