// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Forms
{
    using Startitecture.Orm.Schema;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The Section entity POCO.
    /// </summary>
    [Table("Section", Schema = "forms")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class SectionRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SectionRow"/> class.
        /// </summary>
        public SectionRow()
        {
        }

        /// <summary>
        /// Gets or sets the SectionId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"SectionId", Order = 1, TypeName = "int")]
        [Index(@"PK_Section", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Section ID")]
        public int SectionId { get; set; }

        /// <summary>
        /// Gets or sets the PageId
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"PageId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Page ID")]
        public int PageId { get; set; }

        /// <summary>
        /// Gets or sets the Name (length: 50)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Name", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Order
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Order", Order = 4, TypeName = "smallint")]
        [Required]
        [Display(Name = "Order")]
        public short Order { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent Page pointed by [Section].([PageId]) (FK_Section_Page)
        /// </summary>
        [ForeignKey("PageId")] public PageRow Page { get; set; } // FK_Section_Page
    }

}
// </auto-generated>
