// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Workflow
{
    using Startitecture.Orm.Common;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The WorkflowInstance entity POCO.
    /// </summary>
    [Table("WorkflowInstance", Schema = "workflow")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class WorkflowInstanceRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowInstanceRow"/> class.
        /// </summary>
        public WorkflowInstanceRow()
        {
        }

        /// <summary>
        /// Gets or sets the WorkflowInstanceId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"WorkflowInstanceId", Order = 1, TypeName = "int")]
        [Index(@"PK_WorkflowInstance", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Workflow instance ID")]
        public int WorkflowInstanceId { get; set; }

        /// <summary>
        /// Gets or sets the ProcessVersionId
        /// </summary>
        [Column(@"ProcessVersionId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Process version ID")]
        public int ProcessVersionId { get; set; }

        /// <summary>
        /// Gets or sets the WorkflowStateId
        /// </summary>
        [Column(@"WorkflowStateId", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Workflow state ID")]
        public int WorkflowStateId { get; set; }

        /// <summary>
        /// Gets or sets the Subject (length: 100)
        /// </summary>
        [Column(@"Subject", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Subject")]
        public string Subject { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent ProcessVersion pointed by [WorkflowInstance].([ProcessVersionId]) (FK_WorkflowInstance_ProcessVersion)
        /// </summary>
        [ForeignKey("ProcessVersionId")] public ProcessVersionRow ProcessVersion { get; set; } // FK_WorkflowInstance_ProcessVersion

        /// <summary>
        /// Gets or sets the Parent WorkflowState pointed by [WorkflowInstance].([WorkflowStateId]) (FK_WorkflowInstance_WorkflowState)
        /// </summary>
        [ForeignKey("WorkflowStateId")] public WorkflowStateRow WorkflowState { get; set; } // FK_WorkflowInstance_WorkflowState
    }

}
// </auto-generated>
