// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Workflow
{
    using Startitecture.Orm.Schema;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The WorkflowPhaseInstance entity POCO.
    /// </summary>
    [Table("WorkflowPhaseInstance", Schema = "workflow")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class WorkflowPhaseInstanceRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowPhaseInstanceRow"/> class.
        /// </summary>
        public WorkflowPhaseInstanceRow()
        {
        }

        /// <summary>
        /// Gets or sets the WorkflowPhaseInstanceId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"WorkflowPhaseInstanceId", Order = 1, TypeName = "bigint")]
        [Index(@"PK_WorkflowPhaseInstance", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Workflow phase instance ID")]
        public long WorkflowPhaseInstanceId { get; set; }

        /// <summary>
        /// Gets or sets the WorkflowInstanceId
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"WorkflowInstanceId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Workflow instance ID")]
        public int WorkflowInstanceId { get; set; }

        /// <summary>
        /// Gets or sets the ProcessPhaseId
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"ProcessPhaseId", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Process phase ID")]
        public int ProcessPhaseId { get; set; }

        /// <summary>
        /// Gets or sets the PhaseStateId
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"PhaseStateId", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Phase state ID")]
        public int PhaseStateId { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent PhaseState pointed by [WorkflowPhaseInstance].([PhaseStateId]) (FK_WorkflowPhaseInstance_PhaseState)
        /// </summary>
        [ForeignKey("PhaseStateId")] public PhaseStateRow PhaseState { get; set; } // FK_WorkflowPhaseInstance_PhaseState

        /// <summary>
        /// Gets or sets the Parent ProcessPhase pointed by [WorkflowPhaseInstance].([ProcessPhaseId]) (FK_WorkflowPhaseInstance_ProcessPhase)
        /// </summary>
        [ForeignKey("ProcessPhaseId")] public ProcessPhaseRow ProcessPhase { get; set; } // FK_WorkflowPhaseInstance_ProcessPhase

        /// <summary>
        /// Gets or sets the Parent WorkflowInstance pointed by [WorkflowPhaseInstance].([WorkflowInstanceId]) (FK_WorkflowPhaseInstance_WorkflowInstance)
        /// </summary>
        [ForeignKey("WorkflowInstanceId")] public WorkflowInstanceRow WorkflowInstance { get; set; } // FK_WorkflowPhaseInstance_WorkflowInstance
    }

}
// </auto-generated>
