//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Startitecture.Orm.Testing.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Startitecture.Orm.Testing.Model.FieldsMessages", typeof(FieldsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t revise a form that has not yet been saved..
        /// </summary>
        public static string CantReviseUnsavedForm {
            get {
                return ResourceManager.GetString("CantReviseUnsavedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contract type is invalid for the contract category..
        /// </summary>
        public static string ContractTypeInvalidForContractCategory {
            get {
                return ResourceManager.GetString("ContractTypeInvalidForContractCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form was already submitted..
        /// </summary>
        public static string FormAlreadySubmitted {
            get {
                return ResourceManager.GetString("FormAlreadySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier is an empty GUID..
        /// </summary>
        public static string IdentifierIsEmptyGuid {
            get {
                return ResourceManager.GetString("IdentifierIsEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the ID is less than one..
        /// </summary>
        public static string IdValueLessThanOne {
            get {
                return ResourceManager.GetString("IdValueLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was already added..
        /// </summary>
        public static string ItemAlreadyAdded {
            get {
                return ResourceManager.GetString("ItemAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ordered element could not be found in the list..
        /// </summary>
        public static string OrderedElementNotInList {
            get {
                return ResourceManager.GetString("OrderedElementNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the ordered element is negative..
        /// </summary>
        public static string OrderedElementOrderIsNegative {
            get {
                return ResourceManager.GetString("OrderedElementOrderIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sorted item was already added to the collection..
        /// </summary>
        public static string SortedItemAlreadyAddedToCollection {
            get {
                return ResourceManager.GetString("SortedItemAlreadyAddedToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be null or white space..
        /// </summary>
        public static string StringCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property type is not supported for Unified Fields..
        /// </summary>
        public static string UnifiedFieldPropertyTypeNotSupported {
            get {
                return ResourceManager.GetString("UnifiedFieldPropertyTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Unified Field Source Type is not supported..
        /// </summary>
        public static string UnifiedFieldSourceTypeNotSupported {
            get {
                return ResourceManager.GetString("UnifiedFieldSourceTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown field type cannot have values set..
        /// </summary>
        public static string UnknownFieldTypeCannotHaveValuesSet {
            get {
                return ResourceManager.GetString("UnknownFieldTypeCannotHaveValuesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unsaved form version cannot add a layout..
        /// </summary>
        public static string UnsavedFormVersionCannotAddLayout {
            get {
                return ResourceManager.GetString("UnsavedFormVersionCannotAddLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be converted to the specified value type..
        /// </summary>
        public static string ValueCannotBeConvertedToValueType {
            get {
                return ResourceManager.GetString("ValueCannotBeConvertedToValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow has already been initiated..
        /// </summary>
        public static string WorkflowAlreadyInitiated {
            get {
                return ResourceManager.GetString("WorkflowAlreadyInitiated", resourceCulture);
            }
        }
    }
}
