// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Db", Scope = "type", Target = "SAF.Data.Providers.OleDbCommandAdapter", Justification = "None of the other database libraries use DB.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "SAF.Data.Providers.Database.#Exists`1(System.String,System.Object[])", Justification = "This convention is necessary to use the provider over multiple POCOs.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "SAF.Data.Providers.Database.#Exists`1(System.Object)", Justification = "This convention is necessary to use the provider over multiple POCOs.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "SAF.Data.Providers.DataItemDefinition`1.#Compiled", Justification = "Following the EqualityComparer<T> convention.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "SAF.Data.Providers.DefaultDatabaseFactory`1.#Default", Justification = "Following the EqualityComparer<T> convention.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "SAF.Data.Providers.ExtensionMethods.#ConfigureInsertProcedure`2(SAF.Data.Providers.ProviderMappingProfile`1<!!1>,System.Linq.Expressions.Expression`1<System.Func`2<!!1,!!0>>,System.Func`2<!!1,SAF.Data.Providers.KeyedInsertProcedure`2<!!1,!!0>>)", Justification = "Necessary for fluent method usage.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "SAF.Data.Providers.ExtensionMethods.#ConfigureUpdateProcedure`1(SAF.Data.Providers.ProviderMappingProfile`1<!!0>,System.Func`2<!!0,SAF.Data.Providers.UpdateProcedure`1<!!0>>)", Justification = "Necessary for fluent method usage.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "SAF.Data.Providers.ExtensionMethods.#ConfigureUpdateProcedure`1(SAF.Data.Providers.ProviderMappingProfile`1<!!0>,System.Func`2<!!0,SAF.Data.Providers.UpdateProcedure`1<!!0>>)", Justification = "Necessary for fluent method usage.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "SAF.Data.Providers.ExtensionMethods.#ConfigureDeleteProcedure`1(SAF.Data.Providers.ProviderMappingProfile`1<!!0>,System.Func`2<!!0,SAF.Data.Providers.DeleteProcedure`1<!!0>>)", Justification = "Necessary for fluent method usage.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "SAF.Data.Providers.ExtensionMethods.#ConfigureDeleteProcedure`1(SAF.Data.Providers.ProviderMappingProfile`1<!!0>,System.Func`2<!!0,SAF.Data.Providers.DeleteProcedure`1<!!0>>)", Justification = "Necessary for fluent method usage.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "SAF.Data.Providers.IProcedureConvention.#GenerateName`1(SAF.Data.EntityAction)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "SAF.Data.Providers.Database.#CreateCommand(System.Data.IDbConnection,System.String,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "SAF.Data.Providers.Database.#Insert`1(System.String,System.String,System.Boolean,!!0)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "SAF.Data.Providers.DatabaseTypes.DatabaseType.#ExecuteInsert(SAF.Data.Providers.Database,System.Data.IDbCommand,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "SAF.Data.Providers.DatabaseTypes.FirebirdDatabaseType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "SAF.Data.Providers.DatabaseTypes.MySqlDatabaseType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "SAF.Data.Providers.DatabaseTypes.OracleDatabaseType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "SAF.Data.Providers.DatabaseTypes.OracleDatabaseType.#ExecuteInsert(SAF.Data.Providers.Database,System.Data.IDbCommand,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "SAF.Data.Providers.DatabaseTypes.PostgreSqlDatabaseType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "SAF.Data.Providers.DatabaseTypes.PostgreSqlDatabaseType.#ExecuteInsert(SAF.Data.Providers.Database,System.Data.IDbCommand,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "SAF.Data.Providers.DatabaseTypes.SQLiteDatabaseType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "SAF.Data.Providers.DatabaseTypes.SQLiteDatabaseType.#ExecuteInsert(SAF.Data.Providers.Database,System.Data.IDbCommand,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "SAF.Data.Providers.DatabaseTypes.SqlServerCeDatabaseType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "SAF.Data.Providers.DatabaseTypes.SqlServerDatabaseType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Single", Scope = "member", Target = "SAF.Data.Providers.IDatabaseContext.#Single`1(System.String,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "SAF.Data.Providers.IPocoFactory.#GetTableInfo`1()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "SAF.Data.Providers.IPocoFactory.#GetColumns`1()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "SAF.Data.Providers.IPocoFactory.#CreateDelegate`1(SAF.Data.Providers.PocoDataRequest)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "SAF.Data.Providers.StructuredInsertCommand`1.#InsertInto`1()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "SAF.Data.Providers.IStructuredCommandFactory.#Create`1(SAF.Data.Providers.StructuredCommandText,SAF.Data.Providers.IDatabaseContextProvider)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "SAF.Data.Providers.FlatPocoFactory.#CreateDelegate`1(SAF.Data.Providers.PocoDataRequest)")]

