//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Startitecture.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Startitecture.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t locate assembly &apos;{0}&apos;..
        /// </summary>
        public static string AssemblyNotFound {
            get {
                return ResourceManager.GetString("AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must be decorated with attribute &apos;{1}&apos;..
        /// </summary>
        public static string AttributeRequiredForType {
            get {
                return ResourceManager.GetString("AttributeRequiredForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to navigate to POCO attribute..
        /// </summary>
        public static string BrokenPocoAttributePath {
            get {
                return ResourceManager.GetString("BrokenPocoAttributePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second value must be the same type as the first value..
        /// </summary>
        public static string ComparisonValuesMustBeSameType {
            get {
                return ResourceManager.GetString("ComparisonValuesMustBeSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection factory &apos;{0}&apos; returned a null connection..
        /// </summary>
        public static string ConnectionFactoryReturnedNullConnection {
            get {
                return ResourceManager.GetString("ConnectionFactoryReturnedNullConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find connection type &apos;{0}&apos;. .
        /// </summary>
        public static string ConnectionTypeNotFound {
            get {
                return ResourceManager.GetString("ConnectionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constructor info for the type {0} was null..
        /// </summary>
        public static string ConstructorInfoDoesNotExist {
            get {
                return ResourceManager.GetString("ConstructorInfoDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set primary key {0}.{1} with value &apos;{2}&apos;: {3}.
        /// </summary>
        public static string CouldNotSetPrimaryKeyWithValue {
            get {
                return ResourceManager.GetString("CouldNotSetPrimaryKeyWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database context connection must be a SqlConnection..
        /// </summary>
        public static string DatabaseContextConnectionIsNotSqlConnection {
            get {
                return ResourceManager.GetString("DatabaseContextConnectionIsNotSqlConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insertion of {0} &apos;{1}&apos; failed..
        /// </summary>
        public static string DataItemInsertionFailed {
            get {
                return ResourceManager.GetString("DataItemInsertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delegate could not be created for {0} with the current reader..
        /// </summary>
        public static string DelegateCouldNotBeCreatedWithReader {
            get {
                return ResourceManager.GetString("DelegateCouldNotBeCreatedWithReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token request returned was null or not an HttpWebRequest..
        /// </summary>
        public static string HttpWebRequestNotReturned {
            get {
                return ResourceManager.GetString("HttpWebRequestNotReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index properties are not supported by this method..
        /// </summary>
        public static string IndexPropertiesNotSupported {
            get {
                return ResourceManager.GetString("IndexPropertiesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item could not be added to the collection..
        /// </summary>
        public static string ItemCouldNotBeAddedToCollection {
            get {
                return ResourceManager.GetString("ItemCouldNotBeAddedToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not have matching key property for {1}.{2}.
        /// </summary>
        public static string MatchingKeyPropertyNotFound {
            get {
                return ResourceManager.GetString("MatchingKeyPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no property matching the specified relation..
        /// </summary>
        public static string NoMatchingPropertyForRelation {
            get {
                return ResourceManager.GetString("NoMatchingPropertyForRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query must alias &apos;*&apos; when performing a paged query (e.g., &apos;select t.* from table t order by t.id&apos;)..
        /// </summary>
        public static string OracleQueryMustAliasForPagedQuery {
            get {
                return ResourceManager.GetString("OracleQueryMustAliasForPagedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse SQL statement for paged query..
        /// </summary>
        public static string PagedSqlCouldNotBeParsed {
            get {
                return ResourceManager.GetString("PagedSqlCouldNotBeParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; is not set and cannot be written from {1} &apos;{2}&apos;..
        /// </summary>
        public static string ReadOnlyPropertyCannotBeWrittenTo {
            get {
                return ResourceManager.GetString("ReadOnlyPropertyCannotBeWrittenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider is disposed and cannot be used as a transaction provider..
        /// </summary>
        public static string RepositoryProviderIsDisposed {
            get {
                return ResourceManager.GetString("RepositoryProviderIsDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load type &apos;{0}&apos;: assembly name needed and no assembly name specified..
        /// </summary>
        public static string TypeCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("TypeCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set {0}.{1} to &apos;{2}&apos;: {3}.
        /// </summary>
        public static string UnableToSetPropertyToValue {
            get {
                return ResourceManager.GetString("UnableToSetPropertyToValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or whitespace..
        /// </summary>
        public static string ValueCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
    }
}
