//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Startitecture.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Startitecture.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item failed the validation check. The first of {0} failures was: {1}.
        /// </summary>
        public static string EntityValidationFailedMultiple {
            get {
                return ResourceManager.GetString("EntityValidationFailedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item failed a validation check: {0}.
        /// </summary>
        public static string EntityValidationFailedSingle {
            get {
                return ResourceManager.GetString("EntityValidationFailedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property must have a declaring type..
        /// </summary>
        public static string PropertyMustHaveDeclaringType {
            get {
                return ResourceManager.GetString("PropertyMustHaveDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector cannot be evaluated..
        /// </summary>
        public static string SelectorCannotBeEvaluated {
            get {
                return ResourceManager.GetString("SelectorCannotBeEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service routes were specified..
        /// </summary>
        public static string ServiceRoutesNotSpecified {
            get {
                return ResourceManager.GetString("ServiceRoutesNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one parameter must be specified..
        /// </summary>
        public static string SpecifyAtLeastOneParameter {
            get {
                return ResourceManager.GetString("SpecifyAtLeastOneParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;@{0}&apos; specified but none of the passed arguments have a property with this name (in &apos;{1}&apos;)..
        /// </summary>
        public static string SqlParameterDoesNotMatchArguments {
            get {
                return ResourceManager.GetString("SqlParameterDoesNotMatchArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;@{0}&apos; specified but only {1} parameters supplied (in `{2}`)..
        /// </summary>
        public static string SqlParameterHasNoMatchingValue {
            get {
                return ResourceManager.GetString("SqlParameterHasNoMatchingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not contain property &apos;{1}&apos;..
        /// </summary>
        public static string TypeDoesNotContainProperty {
            get {
                return ResourceManager.GetString("TypeDoesNotContainProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than zero..
        /// </summary>
        public static string ValueMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than or equal to zero..
        /// </summary>
        public static string ValueMustBeZeroOrGreater {
            get {
                return ResourceManager.GetString("ValueMustBeZeroOrGreater", resourceCulture);
            }
        }
    }
}
