//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAF.LocalMachine.Tests.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Test\\SAF\\LocalMachine\\ArchiveFilesCommand\\ArchiveSource")]
        public string ArchiveSourceDirectory {
            get {
                return ((string)(this["ArchiveSourceDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Test\\SAF\\LocalMachine\\ArchiveFilesCommand\\ArchiveTarget")]
        public string ArchiveTargetDirectory {
            get {
                return ((string)(this["ArchiveTargetDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Test\\SAF\\LocalMachine\\ArchiveFilesCommand\\TestFiles")]
        public string SourceFilesDirectory {
            get {
                return ((string)(this["SourceFilesDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Test\\SAF\\LocalMachine\\FileRetentionPolicyManager\\SourceFiles")]
        public string RetentionSourceDirectory {
            get {
                return ((string)(this["RetentionSourceDirectory"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Test\\SAF\\LocalMachine\\FileRetentionPolicyManager\\RetentionTarget")]
        public string RetentionTargetDirectory {
            get {
                return ((string)(this["RetentionTargetDirectory"]));
            }
            set {
                this["RetentionTargetDirectory"] = value;
            }
        }
    }
}
