// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities
{
    using Startitecture.Orm.Schema;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The DataSliceInstance entity POCO.
    /// </summary>
    [Table("DataSliceInstance", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class DataSliceInstanceRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataSliceInstanceRow"/> class.
        /// </summary>
        public DataSliceInstanceRow()
        {
        }

        /// <summary>
        /// Gets or sets the DataSliceInstanceId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"DataSliceInstanceId", Order = 1, TypeName = "int")]
        [Index(@"PK_DataSliceInstance", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Data slice instance ID")]
        public int DataSliceInstanceId { get; set; }

        /// <summary>
        /// Gets or sets the DataSliceId
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"DataSliceId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Data slice ID")]
        public int DataSliceId { get; set; }

        /// <summary>
        /// Gets or sets the Identifier
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Identifier", Order = 3, TypeName = "uniqueidentifier")]
        [Required]
        [Display(Name = "Identifier")]
        public System.Guid Identifier { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent DataSlice pointed by [DataSliceInstance].([DataSliceId]) (FK_DataSliceInstance_DataSlice)
        /// </summary>
        [ForeignKey("DataSliceId")] public DataSliceRow DataSlice { get; set; } // FK_DataSliceInstance_DataSlice
    }

}
// </auto-generated>
