// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities
{
    using Startitecture.Orm.Schema;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The Person entity POCO.
    /// </summary>
    [Table("Person", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class PersonRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PersonRow"/> class.
        /// </summary>
        public PersonRow()
        {
        }

        /// <summary>
        /// Gets or sets the PersonId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"PersonId", Order = 1, TypeName = "int")]
        [Index(@"PK_Person", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Person ID")]
        public int PersonId { get; set; }

        /// <summary>
        /// Gets or sets the FirstName (length: 50)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"FirstName", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets the MiddleName (length: 50)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"MiddleName", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Middle name")]
        public string MiddleName { get; set; }

        /// <summary>
        /// Gets or sets the LastName (length: 50)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"LastName", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Last name")]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets the SecurityIdentifier (length: 254)
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"SecurityIdentifier", Order = 5, TypeName = "nvarchar")]
        [Index(@"UK_Person_SecurityIdentifier", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [MaxLength(254)]
        [StringLength(254)]
        [Display(Name = "Security identifier")]
        public string SecurityIdentifier { get; set; }
    }

}
// </auto-generated>
