// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Startitecture.Platform.Entities.Forms
{
    using Startitecture.Orm.Schema;
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// The TextValueItem entity POCO.
    /// </summary>
    [Table("TextValueItem", Schema = "forms")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial class TextValueItemRow
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextValueItemRow"/> class.
        /// </summary>
        public TextValueItemRow()
        {
        }

        /// <summary>
        /// Gets or sets the TextValueItemId (Primary key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [System.ComponentModel.DataAnnotations.Schema.Column(@"TextValueItemId", Order = 1, TypeName = "bigint")]
        [Index(@"PK_TextValueItem", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Text value item ID")]
        [ForeignKey("FieldValueItem")]
        public long TextValueItemId { get; set; }

        /// <summary>
        /// Gets or sets the Value
        /// </summary>
        [System.ComponentModel.DataAnnotations.Schema.Column(@"Value", Order = 2, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Value")]
        public string Value { get; set; }

        // Foreign keys

        /// <summary>
        /// Gets or sets the Parent FieldValueItem pointed by [TextValueItem].([TextValueItemId]) (FK_TextValueItem_FieldValueItem)
        /// </summary>
        [ForeignKey("TextValueItemId")] public FieldValueItemRow FieldValueItem { get; set; } // FK_TextValueItem_FieldValueItem
    }

}
// </auto-generated>
